In [1]:
import numpy as np 

In [2]:
a=np.array([1,-2,3])
b=np.array([4,6,0], dtype=int)

In [3]:
a

array([ 1, -2,  3])

In [4]:
b

array([4, 6, 0])

In [5]:
c=a+b
c



array([5, 4, 3])

In [7]:
k=np.arange(5)
k

array([0, 1, 2, 3, 4])

In [8]:
print(a.ndim) # razmernost

1


In [9]:
print(a.shape)  #dlina vectora

(3,)


In [36]:
from numpy.linalg import norm
f=norm(a)
f

3.7416573867739413

In [11]:
d_a=norm(a, ord=1)
d_a

6.0

In [12]:
d_a2=norm(a, ord=2)
d_a2

3.7416573867739413

In [13]:
dist=norm(a-b, ord=1) #rasstoyanie m vectorami
dist

14.0

In [14]:
from scipy.spatial.distance import cdist # rabotaet  s vector-stolbtsami i strokami

In [25]:
aa=a.reshape((1,3))  #iz vectora delaet vector stroky
aa

array([[ 1, -2,  3]])

In [27]:
#aa=a.reshape((3,1)) # iz vectora delaet vector stolbets
aa

array([[ 1, -2,  3]])

In [23]:
bb=b.reshape((1,3))

In [26]:
bb

array([[4, 6, 0]])

In [28]:
dd1=cdist(aa,bb, metric='cityblock')
dd1

array([[14.]])

In [30]:
dd2=cdist(a[np.newaxis, :], b[np.newaxis, :], metric='euclidean')
dd2

array([[9.05538514]])

In [33]:
print(a[:,np.newaxis]) # sposob ne menyat razmernost vectorov
print(a[:,np.newaxis].shape)

[[ 1]
 [-2]
 [ 3]]
(3, 1)


In [34]:
np.dot(a,b) #skalyarnoe proizvedenie

-8

In [35]:
a.dot(b)

-8

In [37]:
cos_angle=np.dot(a,b)/(norm(a)*norm(b))
cos_angle

-0.2964997266644405

In [38]:
print(np.arccos(cos_angle))

1.871821803756063
